config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "jobs#index"
  resources :users, only: [:index, :create, :show] do
    collection do
      get :signup
    end
  end
  resources :jobs, only: [:index, :new, :create, :show] do
    resources :messages, only: [:create]
    resources :requests, only: [:index, :new, :create, :show] do
      collection do
        get :submit_index
      end
      resources :dels, only: [:index, :new, :create, :show] do
        member do
          post :purchase
          patch :purchase
        end
        resources :reviews, only: [:create]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/del.rb
class Del < ApplicationRecord
  belongs_to :user
  belongs_to :job
  belongs_to :request
  has_one :review
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :messages
  has_many :jobs
  has_many :requests
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :job
  has_one :del
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :del
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one :job
         has_many :messages
         has_many :requests
         has_many :dels
         has_many :reviews
end

app/controllers/dels_controller.rb
class DelsController < ApplicationController
  before_action :set_request
  before_action :set_job
  def index
    @dels = @request.dels.includes(:user)
  end
  def new
    @del = Del.new
    # @dels = @request.dels.includes(:user)
  end
  def create
    @del = Del.new(del_params)
    if @del.save
      @user = current_user
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end
  def show
    @del = Del.find(params[:id])
  end
  def purchase
    @del = Del.find(params[:id])
  end

  private

  def del_params
    params.require(:del).permit(:name, :text).merge(user_id: current_user.id, job_id: params[:job_id], request_id: params[:request_id])
  end
  def set_request
    @request = Request.find(params[:request_id])
  end
  def set_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end
  def new
    @job = Job.new
  end
  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to root_path
    else
      render :new
    end
  end
  def show
    @job = Job.find(params[:id])
  end

  private

  def job_params
    params.require(:job).permit(:name, :hope_price, :text).merge(user_id: current_user.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_job, only: [:new, :create]
  # def new
  #   @message = Message.new
  #   @messages = @job.messages.includes(:user)
  # end
  def create
    @messages = @job.messages.includes(:user)
    @message = @job.messages.new(message_params)
    if @message.save
      redirect_to job_path(@job)
    else
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id)
  end
  def set_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_job
  def index
    @requests = @job.requests.includes(:user)
  end
  def new
    @request = Request.new
    @requests = @job.requests.includes(:user)
  end
  def create
    @requests = @job.requests.includes(:user)
    @request = @job.requests.new(request_params)
    if @request.save
      redirect_to job_path(@job)
    else
      redirect_to root_path
    end
  end
  def show
    @request = Request.find(params[:id])
  end
  def submit_index
    @user = User.find(current_user.id)
    @requests = @user.requests
  end
  private

  def request_params
    params.require(:request).permit(:name, :price, :del_time, :text).merge(user_id: current_user.id)
  end
  def set_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_del
  def create
    @review = Review.new(review_params)
    if @review.save
      @user = current_user
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:star, :text).merge(user_id: @del.user_id, del_id: @del.id)
  end
  def set_del
    @del = Del.find(params[:del_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to root_path
  end

  def show
    @user = User.find(current_user.id)
    @job = @user.job

    if @job == nil
    else
       @requests = @job.requests
       @dels = @job.user.dels
    end
  end

  def signup
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      redirect_to new_user_registration_path
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :password, :email, :nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deliverables_helper.rb
module DeliverablesHelper
end

app/helpers/dels_helper.rb
module DelsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dels/new.html.haml
= render "layouts/devise-header"
.job-detail-middle
  .job-box
    = form_with model: @del, url: job_request_dels_path(@job.id, @request.id), method: :post, local: true do |f|
      %ul.job-contents
        .jobs-list
          %li 依頼名
          = f.text_field :name
          %li 内容
          = f.text_area :text 
        = f.submit "送信"
= render "layouts/footer"

app/views/dels/purchase.html.haml
= render "layouts/devise-header"
.job-detail-middle
  .job-box
    = form_with model: @review, url: job_request_del_reviews_path(@job, @request, @del), method: :post, local: true do |f|
      %ul.job-contents
        .jobs-list
          %li 評価
          = f.select "review[star]" do
            %option{value: 1} 1
            %option{value: 2} 2
            %option{value: 3} 3
            %option{value: 4} 4
            %option{value: 5} 5
          %li 何かあればご記入下さい
          = f.text_area :text , name: "review[text]"
        = f.submit "レビュー送信"
= render "layouts/footer"

app/views/dels/show.html.haml
= render "layouts/devise-header"
.job-detail-middle
  .job-box
    %ul.job-contents
      .jobs-list
        %li= @del.name
        %li= @del.text
      = form_with model: @del, url: purchase_job_request_del_path(@job, @request, @del), method: :post, local: true do |f|
        = f.submit "購入する"
= render "layouts/footer"

app/views/jobs/index.html.haml
.top-page-body
  = render "layouts/header"
  .top-page-middle
    .jobs-list
      - @jobs.each do |job|
        -# -binding.pry
        = link_to job_path(job.id) do
          .jobs-list__box
            .list-contents
              %ul.left-list
                %li.left-icon
                  =image_tag "icon.png", size: "150x150"
                %li.user-name
                  %span= job.user.nickname
              .right-list
                %ul.right-list-top
                  %li.jobs-title
                    %span= job.name
                  %li.jobs-price
                    希望報酬:¥
                    %span= job.hope_price
                  %li.user-like-ave
                    ★
                    %span= job.user.reviews.average(:star).floor(2).to_f
                %ul.right-list-bottom
                  %li.jobs-text
                    %span= job.text
  = render "layouts/footer"

app/views/jobs/new.html.haml
= render "layouts/devise-header"
.job-new-middle
  .job-box
    %ul.job-contents
      = form_with model: @job, local: true do |f|
        %li タイトル
        = f.text_field :name, value: ''
        %li 希望報酬
        = f.text_field :hope_price, value: ''
        %li 説明文
        = f.text_area :text, value: ''
        = f.submit "以上の内容で掲載する"
= render "layouts/footer"

app/views/jobs/show.html.haml
= render "layouts/devise-header"
.job-detail-middle
  .job-box
    %ul.job-contents
      .jobs-list
        %li= @job.name
        %li.left-icon
          =image_tag "icon.png", size: "150x150"
        %li= @job.user.nickname
        %li 
          希望報酬:
          %span= @job.hope_price
        ★
        %span= @job.user.reviews.average(:star)
        %li= @job.text
      - if @job.messages == nil
        %span メッセージはありません
      - else
        - @job.messages.each do |message|
          .jobs-list__box
            .list-contents
              %ul.left-list
                %li.left-icon
                  =image_tag "gacky.jpg", size: "150x150"
                %li.user-name
                  %span= @job.user.nickname
                %ul.right-list-bottom
                  %li.jobs-text
                    %span= message.text
      = form_with model: @message, url: job_messages_path(@job), local: true do |f|
        = f.text_field :text, name: "message[text]"
        = f.submit "コメントする"
      = form_with model: @message, url: new_job_request_path(@job), method: :get, local: true do |f|
        = f.submit "依頼フォームを送る"
= render "layouts/footer"

app/views/messages/new.html.haml
.top-page-body
  = render "layouts/devise-header"
  .top-page-middle
    .jobs-list
      - if @messages == nil
        %span メッセージはありません
      - else
        - @messages.each do |message|
          .jobs-list__box
            .list-contents
              %ul.left-list
                %li.left-icon
                  =image_tag "gacky.jpg", size: "150x150"
                %li.user-name
                  %span= message.user.nickname
              .right-list
                %ul.right-list-top
                  %li.jobs-title
                    %span= @job.name
                  %li.jobs-price
                    %span= @job.hope_price
                  %li.user-like-ave
                    a
                %ul.right-list-bottom
                  %li.jobs-text
                    %span= message.text
  .footer
    .footer__content
      = form_with model: @message, url: job_messages_path, local: true do |f|
        = f.text_field :text, name: "message[text]"
        = f.submit "送信"

app/views/users/show.html.haml
= render "layouts/devise-header"
.mypage-middle
  .side-bar
    %ul.sidebar-list
      = link_to "", class: "sidelink" do
        %li.side-bar-link
          .side-link-text
            マイページ
      = link_to "", class: "sidelink" do
        %li.side-bar-link
          .side-link-text
            プロフィール
      = link_to "", class: "sidelink" do
        %li.side-bar-link
          .side-link-text
            詳細情報
      = link_to "", class: "sidelink" do
        %li.side-bar-link
          .side-link-text
            お知らせ
      = link_to new_job_path, class: "sidelink" do
        %li.side-bar-link
          .side-link-text
            Job掲載
      = link_to submit_index_job_requests_path(@user, @jod), class: "sidelink" do
        %li.side-bar-link
          .side-link-text
          納品
      - if @requests == nil
        = link_to "", class: "sidelink" do
          %li.side-bar-link
            .side-link-text
              依頼
      - else
        = link_to job_requests_path(@user.job.id), class: "sidelink" do
          %li.side-bar-link
            .side-link-text
              依頼
      = link_to "", class: "sidelink" do
        %li.side-bar-link
          .side-link-text
            収入履歴
      = link_to "", class: "sidelink" do
        %li.side-bar-link
          .side-link-text
            支払い履歴
      = link_to destroy_user_session_path, method: :delete, class: "sidelink" do
        %li.side-bar-link
          .side-link-text
            ログアウト
  .body-page
    マイページです
= render "layouts/footer"