config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "jobs#index"
  resources :users, only: [:index, :create, :show] do
    collection do
      get :signup
    end
  end
  resources :jobs, only: [:index, :new, :create, :show] do
    resources :messages, only: [:create]
    resources :requests, only: [:index, :new, :create, :show] do
      collection do
        get :submit_index
      end
      resources :dels, only: [:index, :new, :create, :show] do
        member do
          post :purchase
          patch :purchase
        end
        resources :reviews, only: [:create]
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/del.rb
class Del < ApplicationRecord
  belongs_to :user
  belongs_to :job
  belongs_to :request
  has_one :review
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :messages
  has_many :jobs
  has_many :requests
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :job
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :job
  has_one :del
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :del
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_one :job
         has_many :messages
         has_many :requests
         has_many :dels
         has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/dels_controller.rb
class DelsController < ApplicationController
  before_action :set_request
  before_action :set_job
  def index
    @dels = @request.dels.includes(:user)
  end
  def new
    @del = Del.new
    # @dels = @request.dels.includes(:user)
  end
  def create
    @del = Del.new(del_params)
    if @del.save
      @user = current_user
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end
  def show
    @del = Del.find(params[:id])
  end
  def purchase
    @del = Del.find(params[:id])
  end

  private

  def del_params
    params.require(:del).permit(:name, :text).merge(user_id: current_user.id, job_id: params[:job_id], request_id: params[:request_id])
  end
  def set_request
    @request = Request.find(params[:request_id])
  end
  def set_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end
  def new
    @job = Job.new
  end
  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to root_path
    else
      render :new
    end
  end
  def show
    @job = Job.find(params[:id])
  end

  private

  def job_params
    params.require(:job).permit(:name, :hope_price, :text).merge(user_id: current_user.id)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_job, only: [:new, :create]
  # def new
  #   @message = Message.new
  #   @messages = @job.messages.includes(:user)
  # end
  def create
    @messages = @job.messages.includes(:user)
    @message = @job.messages.new(message_params)
    if @message.save
      redirect_to job_path(@job)
    else
      redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:text).merge(user_id: current_user.id)
  end
  def set_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_job
  def index
    @requests = @job.requests.includes(:user)
  end
  def new
    @request = Request.new
    @requests = @job.requests.includes(:user)
  end
  def create
    @requests = @job.requests.includes(:user)
    @request = @job.requests.new(request_params)
    if @request.save
      redirect_to job_path(@job)
    else
      redirect_to root_path
    end
  end
  def show
    @request = Request.find(params[:id])
  end
  def submit_index
    @user = User.find(current_user.id)
    @requests = @user.requests
  end
  private

  def request_params
    params.require(:request).permit(:name, :price, :del_time, :text).merge(user_id: current_user.id)
  end
  def set_job
    @job = Job.find(params[:job_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_del
  def create
    @review = Review.new(review_params)
    if @review.save
      @user = current_user
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:star, :text).merge(user_id: @del.user_id, del_id: @del.id)
  end
  def set_del
    @del = Del.find(params[:del_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to root_path
  end

  def show
    @user = User.find(current_user.id)
    @job = @user.job

    if @job == nil
    else
       @requests = @job.requests
       @dels = @job.user.dels
    end
  end

  def signup
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      redirect_to new_user_registration_path
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :password, :email, :nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deliverables_helper.rb
module DeliverablesHelper
end

app/helpers/dels_helper.rb
module DelsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/request_helper.rb
module RequestHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/requests/index.html.haml
= render "layouts/devise-header"
- if @requests == nil
  %span メッセージはありません
- else
  - @requests.each do |request|
    .jobs-list__box
      .list-contents
        %ul.left-list
          %li.user-name
            %span= request.name
          %ul.right-list-bottom
            %li.jobs-text
              %span= request.created_at.strftime("%Y-%m-%d %H:%M")
          = link_to "詳細", "/jobs/#{@job.id}/requests/#{request.id}"

app/views/requests/new.html.haml
= render "layouts/devise-header"
.job-detail-middle
  .job-box
    = form_with model: @request, url: job_requests_path(@job), method: :post, local: true do |f|
      %ul.job-contents
        .jobs-list
          %li 依頼名
          = f.text_field :name
          %li 報酬
          = f.text_field :price
          円
          %li 納期
          = f.text_field :del_time
          日
          %li 内容
          = f.text_area :text 
        = f.submit "送信"
= render "layouts/footer"

app/views/requests/show.html.haml
= render "layouts/devise-header"
.job-detail-middle
  .job-box
    %ul.job-contents
      .jobs-list
        %li= @request.name
        %li.left-icon
          =image_tag "icon.png", size: "150x150"
        %li= @job.user.nickname
        %li 
          提示報酬:
          %span= @request.price
          円
        %li= @request.text
      -# = form_with model: @del, url: new_job_request_del_path(@request), method: :get, local: true do |f|
      -#   = f.submit "依頼を受ける"
      = form_with model: @del, url: "/jobs/#{@job.id}/requests/#{@request.id}/dels/new", method: :get, local: true do |f|
        = f.submit "納品する"
= render "layouts/footer"

app/views/requests/submit_index.html.haml
= render "layouts/devise-header"
- if @requests == nil
  %span 納品はありません
- else
  この依頼の納品が来ています。
  - @requests.each do |request|
    .jobs-list__box 
      = link_to job_request_del_path(@job, request.id, request.del.id) do
        .list-contents
          %ul.left-list
            %li.left-icon
              =image_tag "icon.png", size: "150x150"
            %li.user-name
              %span= request.name
            %ul.right-list-bottom
              %li.jobs-text
                %span= request.text
= render "layouts/footer"